import json
import logging
import yaml
from pathlib import Path
from typing import List, Dict, Any

logger = logging.getLogger(__name__)

COUNTRIES_DICT = {
    "XX": "🏴‍☠️ Unknown",
    "AF": "🇦🇫 Afghanistan",
    "AL": "🇦🇱 Albania",
    "DZ": "🇩🇿 Algeria",
    "AD": "🇦🇩 Andorra",
    "AO": "🇦🇴 Angola",
    "AG": "🇦🇬 Antigua and Barbuda",
    "AR": "🇦🇷 Argentina",
    "AM": "🇦🇲 Armenia",
    "AU": "🇦🇺 Australia",
    "AT": "🇦🇹 Austria",
    "AZ": "🇦🇿 Azerbaijan",
    "BS": "🇧🇸 Bahamas",
    "BH": "🇧🇭 Bahrain",
    "BD": "🇧🇩 Bangladesh",
    "BB": "🇧🇧 Barbados",
    "BY": "🇧🇾 Belarus",
    "BE": "🇧🇪 Belgium",
    "BZ": "🇧🇿 Belize",
    "BJ": "🇧🇯 Benin",
    "BT": "🇧🇹 Bhutan",
    "BO": "🇧🇴 Bolivia",
    "BA": "🇧🇦 Bosnia and Herzegovina",
    "BW": "🇧🇼 Botswana",
    "BR": "🇧🇷 Brazil",
    "BN": "🇧🇳 Brunei",
    "BG": "🇧🇬 Bulgaria",
    "BF": "🇧🇫 Burkina Faso",
    "BI": "🇧🇮 Burundi",
    "KH": "🇰🇭 Cambodia",
    "CM": "🇨🇲 Cameroon",
    "CA": "🇨🇦 Canada",
    "CV": "🇨🇻 Cape Verde",
    "CF": "🇨🇫 Central African Republic",
    "TD": "🇹🇩 Chad",
    "CL": "🇨🇱 Chile",
    "CN": "🇨🇳 China",
    "HK": "🇭🇰 Hong Kong",
    "CO": "🇨🇴 Colombia",
    "KM": "🇰🇲 Comoros",
    "CG": "🇨🇬 Congo",
    "CR": "🇨🇷 Costa Rica",
    "HR": "🇭🇷 Croatia",
    "CU": "🇨🇺 Cuba",
    "CY": "🇨🇾 Cyprus",
    "CZ": "🇨🇿 Czech Republic",
    "DK": "🇩🇰 Denmark",
    "DJ": "🇩🇯 Djibouti",
    "DM": "🇩🇲 Dominica",
    "DO": "🇩🇴 Dominican Republic",
    "EC": "🇪🇨 Ecuador",
    "EG": "🇪🇬 Egypt",
    "SV": "🇸🇻 El Salvador",
    "GQ": "🇬🇶 Equatorial Guinea",
    "ER": "🇪🇷 Eritrea",
    "EE": "🇪🇪 Estonia",
    "ET": "🇪🇹 Ethiopia",
    "FJ": "🇫🇯 Fiji",
    "FI": "🇫🇮 Finland",
    "FR": "🇫🇷 France",
    "GA": "🇬🇦 Gabon",
    "GM": "🇬🇲 Gambia",
    "GE": "🇬🇪 Georgia",
    "DE": "🇩🇪 Germany",
    "GH": "🇬🇭 Ghana",
    "GR": "🇬🇷 Greece",
    "GD": "🇬🇩 Grenada",
    "GT": "🇬🇹 Guatemala",
    "GN": "🇬🇳 Guinea",
    "GW": "🇬🇼 Guinea-Bissau",
    "GY": "🇬🇾 Guyana",
    "HT": "🇭🇹 Haiti",
    "HN": "🇭🇳 Honduras",
    "HU": "🇭🇺 Hungary",
    "IS": "🇮🇸 Iceland",
    "IN": "🇮🇳 India",
    "ID": "🇮🇩 Indonesia",
    "IR": "🇮🇷 Iran",
    "IQ": "🇮🇶 Iraq",
    "IE": "🇮🇪 Ireland",
    "IL": "🇮🇱 Israel",
    "IT": "🇮🇹 Italy",
    "JM": "🇯🇲 Jamaica",
    "JP": "🇯🇵 Japan",
    "JO": "🇯🇴 Jordan",
    "KZ": "🇰🇿 Kazakhstan",
    "KE": "🇰🇪 Kenya",
    "KI": "🇰🇮 Kiribati",
    "KP": "🇰🇵 North Korea",
    "KR": "🇰🇷 South Korea",
    "KW": "🇰🇼 Kuwait",
    "KG": "🇰🇬 Kyrgyzstan",
    "LA": "🇱🇦 Laos",
    "LV": "🇱🇻 Latvia",
    "LB": "🇱🇧 Lebanon",
    "LS": "🇱🇸 Lesotho",
    "LR": "🇱🇷 Liberia",
    "LY": "🇱🇾 Libya",
    "LI": "🇱🇮 Liechtenstein",
    "LT": "🇱🇹 Lithuania",
    "LU": "🇱🇺 Luxembourg",
    "MG": "🇲🇬 Madagascar",
    "MW": "🇲🇼 Malawi",
    "MY": "🇲🇾 Malaysia",
    "MV": "🇲🇻 Maldives",
    "ML": "🇲🇱 Mali",
    "MT": "🇲🇹 Malta",
    "MH": "🇲🇭 Marshall Islands",
    "MR": "🇲🇷 Mauritania",
    "MU": "🇲🇺 Mauritius",
    "MX": "🇲🇽 Mexico",
    "FM": "🇫🇲 Micronesia",
    "MD": "🇲🇩 Moldova",
    "MC": "🇲🇨 Monaco",
    "MN": "🇲🇳 Mongolia",
    "ME": "🇲🇪 Montenegro",
    "MA": "🇲🇦 Morocco",
    "MZ": "🇲🇿 Mozambique",
    "MM": "🇲🇲 Myanmar",
    "NA": "🇳🇦 Namibia",
    "NR": "🇳🇷 Nauru",
    "NP": "🇳🇵 Nepal",
    "NL": "🇳🇱 Netherlands",
    "NZ": "🇳🇿 New Zealand",
    "NI": "🇳🇮 Nicaragua",
    "NE": "🇳🇪 Niger",
    "NG": "🇳🇬 Nigeria",
    "NO": "🇳🇴 Norway",
    "OM": "🇴🇲 Oman",
    "PK": "🇵🇰 Pakistan",
    "PW": "🇵🇼 Palau",
    "PA": "🇵🇦 Panama",
    "PG": "🇵🇬 Papua New Guinea",
    "PY": "🇵🇾 Paraguay",
    "PE": "🇵🇪 Peru",
    "PH": "🇵🇭 Philippines",
    "PL": "🇵🇱 Poland",
    "PT": "🇵🇹 Portugal",
    "QA": "🇶🇦 Qatar",
    "RO": "🇷🇴 Romania",
    "RU": "🇷🇺 Russia",
    "RW": "🇷🇼 Rwanda",
    "KN": "🇰🇳 Saint Kitts and Nevis",
    "LC": "🇱🇨 Saint Lucia",
    "VC": "🇻🇨 Saint Vincent and the Grenadines",
    "WS": "🇼🇸 Samoa",
    "SM": "🇸🇲 San Marino",
    "ST": "🇸🇹 Sao Tome and Principe",
    "SA": "🇸🇦 Saudi Arabia",
    "SN": "🇸🇳 Senegal",
    "RS": "🇷🇸 Serbia",
    "SC": "🇸🇨 Seychelles",
    "SL": "🇸🇱 Sierra Leone",
    "SG": "🇸🇬 Singapore",
    "SK": "🇸🇰 Slovakia",
    "SI": "🇸🇮 Slovenia",
    "SB": "🇸🇧 Solomon Islands",
    "SO": "🇸🇴 Somalia",
    "ZA": "🇿🇦 South Africa",
    "SS": "🇸🇸 South Sudan",
    "ES": "🇪🇸 Spain",
    "LK": "🇱🇰 Sri Lanka",
    "SD": "🇸🇩 Sudan",
    "SR": "🇸🇷 Suriname",
    "SE": "🇸🇪 Sweden",
    "CH": "🇨🇭 Switzerland",
    "SY": "🇸🇾 Syria",
    "TW": "🇹🇼 Taiwan",
    "TJ": "🇹🇯 Tajikistan",
    "TZ": "🇹🇿 Tanzania",
    "TH": "🇹🇭 Thailand",
    "TL": "🇹🇱 Timor-Leste",
    "TG": "🇹🇬 Togo",
    "TO": "🇹🇴 Tonga",
    "TT": "🇹🇹 Trinidad and Tobago",
    "TN": "🇹🇳 Tunisia",
    "TR": "🇹🇷 Turkey",
    "TM": "🇹🇲 Turkmenistan",
    "TV": "🇹🇻 Tuvalu",
    "UG": "🇺🇬 Uganda",
    "UA": "🇺🇦 Ukraine",
    "AE": "🇦🇪 United Arab Emirates",
    "GB": "🇬🇧 United Kingdom",
    "US": "🇺🇸 United States",
    "UY": "🇺🇾 Uruguay",
    "UZ": "🇺🇿 Uzbekistan",
    "VU": "🇻🇺 Vanuatu",
    "VA": "🇻🇦 Vatican City",
    "VE": "🇻🇪 Venezuela",
    "VN": "🇻🇳 Vietnam",
    "YE": "🇾🇪 Yemen",
    "ZM": "🇿🇲 Zambia",
    "ZW": "🇿🇼 Zimbabwe",
}

def generate_prometheus_targets(nodes: List[Dict[str, Any]]) -> List[Dict[str, Any]]:
    """Convert targets to Prometheus file_sd_configs format."""
    prometheus_targets = []

    for node in nodes:
        name = node.get('name')
        if name.startswith('-'):
            continue

        address = node.get('address')
        country = node.get('countryCode', 'XX')

        prometheus_targets.append({
            'targets': [f"{address}:{9100}"],
            'labels': node.get('labels', {
                'name': name,
                'location': COUNTRIES_DICT.get(country, country)
            })
        })

    return prometheus_targets


def save_targets(targets: List[Dict[str, Any]], output_path: str):
    """Save the generated targets to a YAML file."""
    output_dir = Path(output_path).parent
    output_dir.mkdir(parents=True, exist_ok=True)

    with open(output_path, 'w') as f:
        yaml.dump(targets, f, default_flow_style=False, sort_keys=False)

    logger.info(f"Generated targets file: {output_path}")
